[package]
name = "webcrawler"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
lol_html = "2.7.0"
reqwest = "0.12.24"
tokio = { version = "1.48.0", features = ["full"] }
tokio-stream = "0.1.18"
url = "2.5.7"
